version: "3.3"
   
services:
  db:
    image: postgres:13.4
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./db/creation.sql:/docker-entrypoint-initdb.d/creation.sql 
      - ./db/Mall_Customers.csv:/data/Mall_Customers.csv
